### ISSUE TITLE
:sponge: Merger et cleaner les branches

### ISSUE THREAD

**Issue by adriens** [adriens/temps-attente-matrix-led#13]
# :grey_question: Contexte

Cette PR : 

- https://github.com/adriens/temps-attente-matrix-led/pull/5

Est présente depuis longtemps et j'aimerai que les branches soient clean : 

![image](https://github.com/user-attachments/assets/81ec15dc-936a-476e-8205-364f05b365c1)

# :dart: Actions

Merger les branches afin que tout soit aligné et donc plus simple à comprendre quand on arrive sur la repo.

**Comment by raphb3383** [comment]
![{988FD3A3-D42A-46C1-86E6-5055CC1F11E9}](https://github.com/user-attachments/assets/a95c404c-ac40-4bc8-b15d-eba7e911b6f5)

**Comment by adriens** [comment]
Nickel @raphb3383 :pray:
