### ISSUE TITLE
:telescope:  Atelier démo

### ISSUE THREAD

**Issue by adriens** [adriens/temps-attente-matrix-led#14]
# :grey_question: Contexte

Des devs et produits de démo ont été réalisés. Cf : 

- https://github.com/adriens/temps-attente-matrix-led/issues/8#issuecomment-2403310136

Il est donc temps de faire un point sur : 

- L'organisation de la collaboration sur Github : code, issues,milestones
- Les artefacts de demo produits
- Le reste à faire
- Le packaging en produit
- Les news sur l'API

# :dart: Actions

## Prérequis

Ci-dessous pour l'équipe de devs @raphb3383 @josegoue993 : 

Ci-dessous les éléments attendus en prérequis à la bonne tenue de l'atelier:

- [x] Voter pour les créneaux dispo cf https://github.com/adriens/temps-attente-matrix-led/discussions/15
- [x] Toutes les issues bien positionnées sur la milestone [Maquette MVP](https://github.com/adriens/temps-attente-matrix-led/milestone/1) et à jour
- [x] Un document `HOW_TO_INSTALL.md` à la racine de la repo décrivant comment déployer une scène : où positiionner la conf du Wifi, où copier le fichier de la scène (afin que tout personne en possession de la matrice, soit en mesure d'installer le dispositif)
- [ ] :warning: Venir avec du Wifi via partage de votre 4G sinon on sera coincés : la conf doit être prête en amont afin de ne pas galérerle jour J de l'atelier (et le jour J de la demo à l'UNC)
- [ ] Avoir une release` v0.1` laquelle sera utilisée lors de la démo (reprise du fichier .env pour les ID WIFI)

## Atelier

Pour PO @adriens : 

- [x] Sonder pour créneau optimal pour l'atelier
- [x] Planfiier l'atelier
- [ ] Rappel sur les pratiques de dev, code, branche, issues pour optimiser la collab et le suivi de la progression
- [ ] Rappeler le flow : issue->branche->PR-> merge sur `main`
- [ ] faire le point et statuer sur une zone de partage des `mp4` de demo (eg Google drive)
- [ ] Rappel sur les labels et milestones à remplir
- [ ] Faire la revue des issues
- [ ] Faire la demo en live de chaque scène/frame développée et shooter videos et photos
- [ ] Fermer [Maquette MVP](https://github.com/adriens/temps-attente-matrix-led/milestone/1)
- [ ] Prototyper et provisionner la future milestone `v0.2` avec des issues clean et opérationnelles, avec une date de landing
- [ ] Avoir des news plus fraîches sur la date de soutenance
- [ ] Introduire le format de présentation de soutenance

**Comment by adriens** [comment]
@raphb3383 @josegoue993 : à vous de jouer pour choisir le créneau qui matche au mieux la semaine prochaine : 
- https://github.com/adriens/temps-attente-matrix-led/discussions/15
Une fois cela fait, vous pourrez cocher la tâche : 
![image](https://github.com/user-attachments/assets/fb45c556-e51a-4a50-be15-4278513cd876)

... et vous attaquer aux autres tâches des prérequis afin que nous puissions être en conditions optimales le jour J :pray:

**Comment by josegoue993** [comment]
Bonjour @adriens, avec @raphb3383 nous n'avons pas de disponibilité sur les créneaux proposés. Est-il possible d'avoir un créneau à partir de 15h15, le 15/10/2024 ou alors des créneaux la semaine suivante (à partir du 23/10). Merci

**Comment by adriens** [comment]
> Bonjour @adriens, avec @raphb3383 nous n'avons pas de disponibilité sur les créneaux proposés. Est-il possible d'avoir un créneau à partir de 15h15, le 15/10/2024 ou alors des créneaux la semaine suivante (à partir du 23/10). Merci

Yes, j'en rajoute de ce pas :+1:

**Comment by adriens** [comment]
@josegoue993 , Poll mis à à jour, hésitez pas à commenter dessus svp c'est fait pour.

**Comment by raphb3383** [comment]
@adriens 

- Vote créneau OK
- Issues positionnées sur la milestone [Maquette MVP] et à jour
- **HOW_TO_INSTALL.md** disponible à la racine de la repo 
- Partage 4G avec mon téléphone prévu (fonctionnel)
- Release v0.1 disponible sur la branche "code-pimoroni-unicorn" sous le nom **"cosmic_unicorn_script.py"**

Merci

@josegoue993

**Comment by adriens** [comment]
> Release v0.1 disponible sur la branche "code-pimoroni-unicorn" sous le nom "cosmic_unicorn_script.py"

Je ne vois pas de release : 

![image](https://github.com/user-attachments/assets/22d26b74-21f4-461b-9f50-c97fda5a1736)

Quand on merge du code vers `main`, bien penser à passer par une branche, cela permet de générer une releaseNote intéressant de manière automatique. Egalement, toujours mentionner les nums des issues dans les commits et PRs, cela permet de mieux documenter la relaseNote sans effort :sloth:

**Comment by adriens** [comment]
Reste plus qu'à mener l'atelier :+1: 
:pause_button:

**Comment by adriens** [comment]
Atelier mené cf
- #24
