### ISSUE TITLE
:sponge: On ne doit jamais voir de versions de code dans le nom des fichiers :rotating_light: 

### ISSUE THREAD

**Issue by adriens** [adriens/temps-attente-matrix-led#17]
# :grey_question: Contexte

Je vois à la racine les fichiers suivants avec les noms de version dedans et c'est une très mauvaise pratique car les versions d'un même fichier doivent être gérées dans git et non pas via des fichiers individuels : 

![image](https://github.com/user-attachments/assets/1db2973b-9cc2-4b6a-bade-caa8ecf56498)

:point_right: Toute version doit être géré par des commits, tags et releases : 

![image](https://github.com/user-attachments/assets/42662b75-f73c-4722-8064-45ba21a0de47)
![image](https://github.com/user-attachments/assets/8eb183e9-dad3-449d-9f1b-9f7f24b98f2a)

# :dart: Action

- [x] Déplacer les codes source sour `src`  la racine du projet afin que la racine du projet soit propre et compacte (on garde le README, le HOW_TO_INSTALL,...)
- [x] Si ces scènes sont des produits finaux totalement indépendants alors les renommer en conséquence 
- [x] Mener les actions recommandées par rapport au versioning

**Comment by adriens** [comment]
@raphb3383 stp mettre à jour le status des actions et fermer si :ok: 
![image](https://github.com/user-attachments/assets/dc541206-ae0b-42b5-ba3d-f69b491b9fd3)

**Comment by raphb3383** [comment]
=> déplacement de sources sous "src"
=> renommage OK
=> version 0.1 mise à jour
