### ISSUE TITLE
🧽 Eliminer les accès à l'endpoint `/csv`

### ISSUE THREAD

**Issue by adriens** [adriens/temps-attente-matrix-led#35]
# ❔ Contexte

Aujourd'hui, dans `main/src/main.py` fait appel à un endpoint qui sera prochainement décommissionné comme rappelé dès la premirèe démo cf code ci-dessous : 

```python
def get_agency_data(api_key):
    """Récupère les données des agences en utilisant l'API avec la clé fournie."""
    url = "https://api.opt.nc/temps-attente-agences/csv"  # URL de l'API qui fournit les données des agences
    headers = {"x-apikey": api_key}  # Ajoute l'API Key aux en-têtes HTTP pour l'authentification
    try:
```

Il faut passer par l'endpoint renvoyant du `json` pour renvoyer les agences.

# 🎯 Action

Basculer la partie de feed des agences vers l'appel REST/json.

**Comment by raphb3383** [comment]
Bonjour,

ça fait 3 jours que je suis sur cette modification pour le changement d'Endpoint en passant par https://api.opt.nc/temps-attente-agences/temps-attente/agence/{agency_id}.

Je n'ai pas gardé la première logique :
- 1 Endpoint qui récupère le listing des agences [https://api.opt.nc/temps-attente-agences/temps-attente/agences]
- 1 Endpoint qui met à jour la valeur du temps d'attente [https://api.opt.nc/temps-attente-agences/temps-attente/agence/{agency_id}.]
=> limite du Raspberry (problème d'occupation mémoire lors de la récupération d'info du premier endpoint).

Pour optimisé l'utilisation du Raspberry afin de ne pas le surcharger, je suis parti sur un fichier "agences.env" avec un listing d'agence couplé à l'utilisation de https://api.opt.nc/temps-attente-agences/temps-attente/agence/{agency_id} 
=> Cela devait être simple mais je bloque sur la boucle d'affichage.... je ne comprend pas/plus le script

Je reprend la semaine prochaine (si mon volume de travail le permet).


@adriens @josegoue993

**Comment by adriens** [comment]
> Pour optimiser l'utilisation du Raspberry afin de ne pas le surcharger, je suis parti sur un fichier "agences.env" 

je ne comprends pas car le fichier .env est destiné à stocker des variables d'environnements. or une collection d'agences n'est pas cela.
J'en déduis qu'au bout tu génères une fichier avec la collection des agences ?

Bien joué pour le refactoring, on bosse pas mal sur le backend ces jours-ci. On pourra shooter un maxm de videos et images mercredi prochain :sunglasses:
