### ISSUE TITLE
:camera_flash: Remplacer QrCode de la repo GH par QrCode projet hackster

### ISSUE THREAD

**Issue by adriens** [adriens/temps-attente-matrix-led#37]
# :grey_question: Contexte

Cf : 

- #25 

Notre projet IoT devient un produit et donc il doit décrire une plateforme adaptée comment il a été construit afin que toute personne intéressée puisse utiliser cette recette.

Actuellement, le QrCode fonctionne mais pointe vers la repo gh : 

- #22 

# :dart: Action

Remplace l'url cible par celle-ci https://bit.ly/3YZZRkJ afin que lorsque l'on flashe le device, on tombe sur la page du projet sur Hacksert.io.

**Comment by raphb3383** [comment]
@adriens 

Le QR code a été modifié afin de pouvoir arrivé sur la page du projet "Hacksert.io"

https://github.com/user-attachments/assets/efe214bd-6b88-443f-b0d6-fd1b8f37444a

**Comment by adriens** [comment]
Nickel et en bonus, c'est bien responsible sur mobile.
j'ai invité un nouveau specateur pour la demo de notre MVP demain.ça fait des curieux.
J'ai dit que ce que j'avais vu ce week-end envoyait du pâté :star_struck:
