### ISSUE TITLE
:octocat: Comptes GH des devs

### ISSUE THREAD

**Issue by adriens** [adriens/temps-attente-matrix-led#6]
- [x] Récupérer le compte GH de Raphael Bordais
- [x] Récupérer le compte GH de José Goue
- [x] Inviter sur la repo
- [x] Profile GH de @raphb3383 
- [x] Profile GH de @josegoue993 

# :bookmark: Ressources

- [Managing your profile README](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-profile/customizing-your-profile/managing-your-profile-readme)
- https://github.com/abhisheknaiidu/awesome-github-profile-readme
- [GitHub Profile README Generator](https://rahuldkjain.github.io/gh-profile-readme-generator/)
[Star this repo21174](https://github.com/rahuldkjain/github-profile-readme-generator)

**Comment by josegoue993** [comment]
Bonjour Adrien, voici mon compte GitHub. José

**Comment by raphb3383** [comment]
Bonjour à tous,

Voici mon compte GH.

Merci et bonne journée.

**Comment by adriens** [comment]
:ok_hand: , il faudra accepter les invitations @josegoue993 @raphb3383 : 
![image](https://github.com/user-attachments/assets/6058917e-c53a-47e5-a26f-65ea38900105)

**Comment by raphb3383** [comment]
Bonsoir,

Merci pour l'invitation, que j'ai acceptée.

J'ai implémenté rapidement un premier code pour se donner une idée pour la charte graphique discutée lors du kickoff (capacités...).
Des sources, scripts et vidéo ont également été ajoutés sur ce dépot.

Merci et bonne soirée.

**Comment by adriens** [comment]
> Merci pour l'invitation, que j'ai acceptée.

Top, tu pourras te faire un profil bien clean et cool ... et merger : 

- https://github.com/adriens/temps-attente-matrix-led/pull/5


> J'ai implémenté rapidement un premier code pour se donner une idée pour la charte graphique discutée lors du kickoff (capacités...).
> Des sources, scripts et vidéo ont également été ajoutés sur ce dépot.

:ok_man: Je vois en effet des branches : tu peux faire les PRs afin de ne pas multiplier les branches parallèles et complexifier la gestion du projet spt ? :pray:

**Comment by adriens** [comment]
@raphb3383 , tu pourras merger les branches et organiser le code stp ? Là, y'en a beaucoup trop : 

![image](https://github.com/user-attachments/assets/6c696992-8ebb-4e2b-8b06-0d3b294dfbd0)

**Comment by adriens** [comment]
@raphb3383 @josegoue993 , pouvez-vous svp mettre à jour vos profils avec un avatar et pour toi @josegoue993 générer un README de profil svp.
Status actuel : 

![image](https://github.com/user-attachments/assets/dd49d401-fb8c-40a5-be2d-17b8fb8430d7)
![image](https://github.com/user-attachments/assets/89da62b7-9b1f-4120-812c-a6a32438f331)

Le projet ayant démarré, je souhaite que nous soyons clean sur cette issue des comptes GH :pray:
