### ISSUE TITLE
FAQ

### ISSUE THREAD

**Issue by raphb3383** [adriens/temps-attente-matrix-led#7]
Bonjour Adrien,

Tes remarques ont été prises en compte et traitées.

Pour l'instant la maquette ressemble à ça : 

![maquette](https://github.com/user-attachments/assets/b7be4622-cf04-4eb0-959b-55e15459fe52)

=> OK pour les agences et la récupération de l'ID/Nom

=> OK pour la référence "realMaxWaitingTime" qui servira de base pour la définition du temps d'attente dans les agences.

Merci.

**Comment by adriens** [comment]
Hello, non, tu n'as pas besoin de docker, tu consommes direct l'API depuis le portail depuis le www. Donc c bcp plus simple : la matrice se connecte en wifi au web et consomme l'API.

Donc en gros, faut  : 

1. aller ici : https://apigee-optnc-prd-api.apigee.io/
2. Suivre le tuto https://dev.to/optnc/apigee-101-onboarding-authentication-1ghl
3. déployer le code depuis le PC sur le rpi de la matrix
4. Tout déconnecter
5. laisser tourner le device tt seul

Donc pas de `httpie`, ça c'est juste pour développer, mais c inutile de mentionner et pas de docker.

**Comment by raphb3383** [comment]
Salut,

Bien pris pour tes remarques. J'étais parti sur un environnement local avec Docker...

La maquette est dans cette état là :

![image](https://github.com/user-attachments/assets/9ceb906f-ef41-4106-8995-607669776517)

-> un environnement sans la tablette afin de pouvoir tester différentes scripts

exemple pour Spyder :
![{D8B91052-F097-452C-A64F-02B3EFD2EC71}](https://github.com/user-attachments/assets/faf348f6-b604-4156-874d-599190d07eba)

-> un environnement projet avec la tablette

[Snapshot Thonny/tablette sera rajouté plus tard]

Pour le reste, on est sur la même idée.

Merci.

**Comment by adriens** [comment]
Ah yes, alors évitez de passer par le csv, interroger uniquement la data/json :pray:

**Comment by adriens** [comment]
Remplacer Spyder qui est un ide par [MicroPython](https://micropython.org/) est plus approprié : 

![image](https://github.com/user-attachments/assets/7519e9f9-0662-4b47-a0c7-3916cfdd94e0)

**Comment by adriens** [comment]
Tu pourras sortir un diagramme qui ne présente que le produit final matrix en autonome et tape l'API avec logo APIGEE ? **:point_right: Car ce sera l'architecture cible et je valoriserai cela avec Google**

**Comment by adriens** [comment]
Issue non compliante avec les bonnes pratiques de gestion di'ssue et milestones.
