### ISSUE TITLE
Avancement

### ISSUE THREAD

**Issue by raphb3383** [adriens/temps-attente-matrix-led#8]
Etat actuel de la matrice :

# **Charte graphique de la tablette : 90%**

# **Process Frame 1 : 90%**

# **Process frame 2 : 90%** 

# **Process frame 3 : 90%**

**Comment by adriens** [comment]
Hello, peux-tu stp transformer les étapes en issues GH au sein d'une milestone et sur chacune des process si tu as un truc, une video.

En gros une frame->une issue-> un ensemble de videos

:point_right: AInsi je pourrai suivre efficacement. Tu peux t'insiper de ça si tu veux : https://github.com/adriens/temps-attente-streamlit/milestones


> Requête API pour le temps d'attente en agence (là je ne sais pas trop où chercher...)

https://apigee-optnc-prd-api.apigee.io/docs/temps-dattente-en-agence-opt/1/overview

![image](https://github.com/user-attachments/assets/ada257e0-cdf6-446c-80f2-fed895b14e51)

**Comment by adriens** [comment]
Egalement les issues doivent toujours être assignées et avec des labels
![image](https://github.com/user-attachments/assets/d787a4b1-f8f0-42a9-ba49-a71ce0160787)

**Comment by adriens** [comment]
> Process Frame 1 :
> Affichage sigle OPT : OK
> Heure affiché : OK
> => réalisation 90%

Quels sont les 10% manquants? As-tu des videos live stp ? Même très courte ? Et quelle branche : les commits doivent être rattachés aux issues

![image](https://github.com/user-attachments/assets/d24362cf-a246-45e6-8f3e-1b9962984116)

**Comment by raphb3383** [comment]
# Exécution principale
Le programme se connecte au Wi-Fi, initialise l'écran Cosmic Unicorn, puis lance la boucle principale pour afficher les données d'attente des agences et l'heure. 

# Principe du script 

**Imports**
Le script utilise divers modules pour la gestion réseau, l'affichage sur l'écran Cosmic Unicorn, la synchronisation de l'heure (NTP), et les requêtes API.

**Constantes (COLORS)**
Définit des couleurs (en RGB) qui seront utilisées pour l'affichage sur l'écran Cosmic Unicorn.

**Fonction load_api_key(file_path)**
Charge la clé API à partir d'un fichier .env.
Si le fichier est introuvable ou illisible, retourne None.

**Classe CosmicUnicornDisplay**
Cette classe gère l'affichage sur l'écran Cosmic Unicorn, avec plusieurs méthodes dédiées aux différentes parties de l'affichage.

- __init__() :
Initialise l'écran et les couleurs, configure la police et prépare l'affichage pour l'animation et le texte défilant.

- clear() :
Efface l'écran en mettant un fond noir.

- update() :
Met à jour l'écran avec les nouvelles informations.

- set_pen(color) :
Définit la couleur du stylo pour les dessins ou textes affichés.

- scroll_text(message) (Frame 3) :
Gère le texte défilant dans la frame 3 en bas de l'écran.

- draw_frame(y_start, y_end, color) :
Dessine un cadre rectangulaire autour de certaines sections de l'écran.

- draw_text_opt() (Frame 1) :
Affiche le texte "OPT" en haut de l'écran (frame 1).

- draw_smiley(mood) :
Dessine un smiley (heureux, neutre ou triste) selon les temps d'attente.

- display_digit(digit, col_start, row_start, color) :
Affiche un chiffre à une position spécifique sur l'écran.

- display_clock(start_time, synced) (Frame 1) :
Affiche l'heure dans le fuseau horaire GMT+11.

- set_transition_variable(name) :
Met à jour la variable de transition pour le texte défilant.

- display_message_frame_2(message) (Frame 2)
Affiche un message statique centré dans la frame 2 (milieu de l'écran).

- Fonction check_network_connection()
Vérifie si une connexion réseau est active en envoyant une requête simple à Google.

**Fonction get_agency_data(api_key)**
Récupère les données des agences (temps d'attente) depuis une API en utilisant la clé API fournie.

**Fonction parse_csv_data(csv_content)**
Analyse les données CSV renvoyées par l'API pour extraire les identifiants d'agences, noms et temps d'attente.

**Fonction connect_wifi(ssid, password)**
Connecte l'appareil à un réseau Wi-Fi en utilisant un SSID et un mot de passe.

**Fonction sync_time()**
Synchronise l'heure de l'appareil avec des serveurs NTP pour garantir l'heure correcte.

**Fonction main_loop(display, start_time, synced)** // Boucle principale du programme :
- Vérifie la connexion réseau.
- Synchronise l'heure via NTP.
- Affiche le texte 'OPT' (frame 1), 
- Affiche les données d'attente des agences et l'heure. Parcourt les agences :
                              un smiley en fonction du temps d'attente (frame 2)
                              affiche leur nom défilant (frame 3)

**Comment by adriens** [comment]
Hello @raphb3383 , essaie de privilégier la livraison d'un code/fichier dans lequel chaque fonction se dcrit elle-même, directement dans les commentaires du code source.

**Comment by raphb3383** [comment]
Salut @adriens , 

Bien pris, j'ai posé cet issue car ça me servira à expliquer le script pour les livrables. Si cela dérange, je peux garder cela en local.

**Comment by adriens** [comment]
> => possible de caler un RDV pour faire une démonstration ?

Avec tte la team tu veux dire ?

**Comment by adriens** [comment]
Je vais transformer cette action en issue. 
Je vous montrerai comment améliorer la collaboration et gérer les issues

**Comment by adriens** [comment]
@raphb3383 : je vous ai préparé des actions à mener en prérequis à l'atelier  : 
- https://github.com/adriens/temps-attente-matrix-led/issues/14

**Comment by raphb3383** [comment]
@adriens 

Bien pris pour les actions à mener.

Pour les objectif de cette semaine :
=> Bouton B : pour rester sur l'affichage de l'agence en cours : OK
=> Bouton C : pour changer le type de smiley : à définir car le rendu n'est pas top si autre chose qu'un smiley
=> Bouton D : pour changer le jeu de couleur : à définir
=> Bouton volume et luminosité : OK

=> je mettrais en place le "HOW_TO_INSTALL.md" pas avant mercredi prochain, je n'ai pas de dispo avant.
=> Le partage avec ma connexion 4G est OK
=> La release v0.1 est en place (sans les fonction des bouton C et D) (pull sur la branche "code-pimoroni-unicorn" en tant que "matriceLED9.py")

Visu release v0.1 :


https://github.com/user-attachments/assets/89db1376-d910-44ab-8567-cc29b7010fb1



@josegoue993

**Comment by adriens** [comment]
Punaise @raphb3383 , là tu m'as bien teasé et la video est bien clean.

On commence à voir le produit émerger, ça me donne des idées pour le protocole de la soutenance en mode startup et voir un effet WOW.
On va même pouvoir développer un manuel et tout, c'est du très beau boulot. Egalement , je sais comment tu as shooté la video cette fois, mais c bcp mieux :+1: 
Grâce à cette version, on va pouvoir prendre plein de feedback, par exemple sur le processus de boot qu ipourrait avoir une petite animation de _truc qui tourne_ ou un logo OPT-NC qui s'affiche mais dont l'intensité lumineuse varie avec le temps afin de montrer que queque'chose se charge.


> Pour les objectif de cette semaine :
> => Bouton B : pour rester sur l'affichage de l'agence en cours : OK
> => Bouton C : pour changer le type de smiley : à définir car le rendu n'est pas top si autre chose qu'un smiley
> => Bouton D : pour changer le jeu de couleur : à définir
> => Bouton volume et luminosité : OK
> 

Idéalement on aurait du avoir des issues dédieés, positionnées sur une milestone et ainsi, le reporting se ferait tout seul. On travaillera ça lors de l'atelier, c'est pas compliqué.

Je ne m'attendais pas à c que tu ailles aussi vite sur l'interactiivté sur les boutons :clap: 


> => je mettrais en place le "HOW_TO_INSTALL.md" pas avant mercredi prochain, je n'ai pas de dispo avant.

C'est nickel :ok_hand: 

> => Le partage avec ma connexion 4G est OK

Parfait, comme ça on se met en conditions pour la soutenance... et également nous permettra de valoriser :point_right: que cette solution marche partout où on a de la 4G... et ça c'est vraiment top :sunglasses: 
A la liite, il ne manquerait plus qu'avoir une alim autonome genre solaire ou autre mais là j'y connais pas grand chose : tet que toi @raphb3383 ou @josegoue993 avaient des billes ? 

=> La release v0.1 est en place (sans les fonction des bouton C et D) (pull sur la branche "code-pimoroni-unicorn" en tant que "matriceLED9.py")

Yes, penses juste à merger la PR puis à créer une release et ce sera :ok:

**Comment by raphb3383** [comment]
Bonsoir @adriens ,

Juste pour prévenir que le merge a été fait et une release v0.1 est disponible.
Le fichier "HOW_TO_INSTALL.md" est disponible, est-il OK ?

J'ai aussi fait une sorte d'arbre pour expliquer le script, est-il clair ?

![script](https://github.com/user-attachments/assets/5ed17ba1-617d-4976-b178-11d7b02ebb34)

On voit pour une batterie externe USB pour la démo.

Merci.

@josegoue993

**Comment by adriens** [comment]
@raphb3383 : 
- https://github.com/adriens/temps-attente-matrix-led/issues/17

**Comment by adriens** [comment]
> J'ai aussi fait une sorte d'arbre pour expliquer le script, est-il clair ?

yes, il est très clair, mais pourrais-tu le générer [au sein d'un markdown, à l'aide de mermaid](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-diagrams) afin que ce soit géré comme un code source (dynamique donc) au lieu d'une image (statique)

**Comment by adriens** [comment]
@raphb3383 : veiller  à toujours avoir un assigné aux issues stp 
![image](https://github.com/user-attachments/assets/a84c8e75-b079-4f1e-a05e-8aac4ee44e55)

**Comment by adriens** [comment]
> "On voit pour une batterie externe USB pour la démo."

Top, c'est un nice to have, pas de prise de tête si on a pas. Au pire on peut alimenter avec un laptop :thinking:

**Comment by raphb3383** [comment]
Bonjour @adriens 

La release du script à été mis à jour (fonctionnement Wifi avec crédential dans fichier .env), la tablette est bien autonome et le script fonctionne correctement. 

On a rajouté un script "boot.py" pour lancer "main.py" (nomenclature Pimoroni). Cette structure permet de garder de la liberté en définissant ce que l'on veut lancer à partir de ce fichier "boot.py". Maintenant on peut très bien fusionner le "main" dans le "boot" et n'en faire qu'un seul...

On a modifié en conséquence le "HOW_TO_INSTALL" en prenant aussi tes remarques.

Pour l'arbre de fonctionnement du script, on est donc passé par Mermaid et le rendu est sur "SCRIPT-PLAN.md".

On est en train de voir pour la batterie USB pour la présentation de mercredi prochain.

Bon weekend.

@josegoue993

**Comment by adriens** [comment]
> La release du script à été mis à jour (fonctionnement Wifi avec crédential dans fichier .env), la tablette est bien autonome et le script fonctionne correctement.

Yes, j'ai vu ça :+1: 

> On a rajouté un script "boot.py" pour lancer "main.py" (nomenclature Pimoroni). Cette structure permet de garder de la liberté en définissant ce que l'on veut lancer à partir de ce fichier "boot.py"

Je me suis douté d'un truc dans le genre. Ca pourrait être intéressant de définir un ensemble de variables statiques avec un fichier vers lequel pointer par défaut. Un truc du genre : 

```python
import machine

# Définir les constantes
APP_MAIN = 'main.py'
MAIN_STATIC_LOGO_OPTNC = 'logo_optnc.py'
MAIN_STATIC_LOGO_UNC = 'logo_unc.py'
MAIN_PROJECT_QRCODE = 'project_qrcode.py'
MAIN = APP_MAIN  # MAIN prend la valeur de APP_MAIN

# Appel de l'animation
machine.main(MAIN)
```

> On a modifié en conséquence le "HOW_TO_INSTALL" en prenant aussi tes remarques. (Les photos et vidéos seront insérées plus tard).

Yes, on fera une récolte de video et photos semaine prochaine :+1: 

> Pour l'arbre de fonctionnement du script, on est donc passé par Mermaid et le rendu est sur "SCRIPT-PLAN.md".

Yes, je l'ai vu (faudra juste plus parler de tablette mais de matrice led car les gens pensent à une tablette tactile.. alors que nous... on fait du LED en IoT :sunglasses: )

![image](https://github.com/user-attachments/assets/180ff130-6316-41a9-9576-71cdcd156a8b)


> On est en train de voir pour la batterie USB pour la présentation de mercredi prochain.

C'est bonus, vous cassez pas trop la tête avec ça. Par contre, on pourra phosphorer pour maximiser notre impact pour la demo le Jour J.

> Bon weekend.

yes, merci vous aussi. Y'aura un invité surprise ancien de l'UNC :smiley_cat:

**Comment by adriens** [comment]
Issue fermée car on ne fait pas des issues d'avancement cf bonnes pratiques d'issue management et miletones.
