### ISSUE TITLE
:popcorn:  Charte graphique :art: 

### ISSUE THREAD

**Issue by raphb3383** [adriens/temps-attente-matrix-led#9]
# Charte graphique pour la Frame 1 : 
SIGLE "OPT" à gauche et heure affiché à droite

# Charte graphique pour la Frame 2 : 
Smiley avec humeur (Happy/neutral/sad) et code couleur sur humeur (vers/jaune/rouge)

# Charte graphique pour la Frame 3 : 
Défilement nom agence associé à humeur smiley

# A faire valider :
**-> Police**

**-> Codes couleur**
Le code couleur RVB est à définir pour les couleurs suivantes 
- YELLOW: (251, 189, 8)
- WHITE: (255, 255, 255)
- BLUE: (40, 44, 131)
 -GREEN: (0, 255, 0)
 -BLACK: (0, 0, 0)
- RED: (255, 0, 0)
- EYE_COLOR: (0, 0, 255)
- GREEN_SMILEY: (34, 177, 76)
- YELLOW_SMILEY: (255, 242, 0)
- RED_SMILEY: (237, 28, 36)

**-> disposition des frames**
Rapport hauteur tablette : 25% - 50% - 25%

# => réalisation 90%

# Restant à faire :

=> **Si la police, la couleur et la disposition des éléments convient, on peut dire que cette partie "Graphique" est validée.**
=> **Problème d'affichage entre le smiley des agences (lag dû au temps d'update API JSON/DATA pour la mise à jour du temps d'attente de l'agence affiché)**
=> **Problème d'affichage lors de l'émission du son d'humeur (durant le son, l'affichage horloge, smiley et scroll vacille)**

**Comment by adriens** [comment]
Où sont les visuels et les codes source ?

**Comment by raphb3383** [comment]
Rendu des différents écrans possibles au lancement du script 

![no-wan](https://github.com/user-attachments/assets/4dc39f5c-bd5a-452c-ac6b-9c9f5b5fac06)
![no-api](https://github.com/user-attachments/assets/ac0da2b3-3c7b-403d-85c6-9f5943cea86c)
![wait](https://github.com/user-attachments/assets/ceff54f4-5061-4dbc-a3c4-d0519cb5650b)

et une vidéo d'exécution du script

**Comment by adriens** [comment]
>  Il reste quelques coquilles mais le principe est là. On peut remarquer le changement d'état à partir de 1:25.

Oui, c'est très bien, no souci. Je peux me projeter sur ces élémnts :clap: 


:point_down: Je n'rrive pas à télécharger le mp4 : 
![image](https://github.com/user-attachments/assets/2dd17885-f15f-4f1a-b70f-2e8fd3d91db7)

**Comment by adriens** [comment]
@raphb3383 c good, j'arrive à voir la video, c super :star_struck:

**Comment by adriens** [comment]
![image](https://github.com/user-attachments/assets/17c63f32-cd3e-4674-80cd-fa0c3d0c3a7c)

**Comment by adriens** [comment]
Je galère à lire le mp4 depuis mon linux, mais OK depuis mon :iphone:

**Comment by adriens** [comment]
@raphb3383 : tu pourras mettre des titres plus parlants aux issues stp ?

**Comment by raphb3383** [comment]
Bonjour,

Pour la conception graphique, nous avons avancé et vous proposons cette version qui, si elle est validée, sera la 1.0.

La vidéo ci-dessous expose en parallèle le rendu visuel ainsi que les logs pour apprécier le retour des étapes du script.


https://github.com/user-attachments/assets/523b4a58-cac4-48d4-b474-f0cc1de64514


=> **Si la police, la couleur et la disposition des éléments convient, on peut dire que cette partie "Graphique" est validée.**

**Comment by adriens** [comment]
:star_struck: @raphb3383 , punaise, ça marche :heavy_heart_exclamation: 
Et tu fais défiler les agences.

De notre côté, on a fait évoluer l'API ce jour : jettez un oeil et vous verrez du neuf dans les champs :sunglasses: Comme le noombre de personne en attente....

**Comment by adriens** [comment]
Charte fixée : tu peux fermer stp @raphb3383 ?
